name: qr_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.2
  localstore: ^1.4.0
  loader_overlay: ^4.0.3
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  ip_country_lookup: ^1.0.3
  network_info_plus: ^6.1.2
  flutter_nfc_kit: ^3.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
